### ISSUE TITLE
虽说app上有salt的格式说明，但是如果在命令行里运行，最好也给个简短格式说明

### ISSUE THREAD

**Issue by kangdalei** [zhoilet/Password#2]
https://github.com/zhoilet/Password/blob/3a9c3e3cabeb9e061e3427e44b8891443b3e7fe8/password.py#L45

**Comment by zhoilet** [comment]
你好！

我已经更改了文件。在用户输入错的salt导致程序crash之后，程序会提醒用户去看instructions。

谢谢你的意见！
